import localFont from "next/font/local";
import "./globals.css";
// import "../../styles/globals.scss"
import {NextUIProvider} from "@nextui-org/react";
import Nav from '@/components/nav';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextUIProvider>
          <>
            <Nav/>
            <div className="container mx-auto">
            {children}
            </div>
          </>
        </NextUIProvider>
      </body>
    </html>
  );
}
